"""link projects and chat sessions

Revision ID: 6494d945750e
Revises: b2d3cd96b462
Create Date: 2026-05-30 19:15:55.132562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6494d945750e'
down_revision: Union[str, Sequence[str], None] = 'b2d3cd96b462'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'chat_sessions', 'research_projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.drop_column('chat_sessions', 'project_id')
    # ### end Alembic commands ###
